<a href="https://colab.research.google.com/github/aisaiahmaguadog/cmsi5350-notes/blob/main/Notebooks/Notebook_2_2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔢 Numpy

## Learning Objectives

Students will be able to:

* Create a **numpy array**
* Initialize a **multi-dimensional** numpy array
* **Index and slice** into a numpy array
* **Reshape** a multi-dimensional numpy array
* **Concatenate** and **transpose** a numpy array


## Introduction to NumPy
NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides:

* A powerful N-dimensional array object (ndarray)
* Mathematical functions for arrays
* Tools for working with arrays
* Much faster computation compared to pure Python

**Why NumPy?**

* Performance: NumPy arrays are much faster than Python lists for numerical operations
* Memory Efficiency: Arrays use less memory than lists
* Vectorization: Apply operations to entire arrays without writing loops
* Broadcasting: Perform operations on arrays with different shapes

Let's start by importing NumPy:

In [2]:
# Import NumPy
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.5.3


## 1. Create a NumPy Array

Different methods to create NumPy arrays from scratch.


Method 1: From Python lists

[`np.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html): Create an array.





In [ ]:
# Method 1: From Python lists
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)

print("1D array from list:", array_1d)
print("Type:", type(array_1d)) #class object
print("Shape:", array_1d.shape)
print("Data type:", array_1d.dtype)

Method 2: Using NumPy functions

[`np.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html): Return a new array of given shape and type, filled with zeros.

[`np.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html): Return a new array of given shape and type, filled with ones.

[`np.full()`](https://numpy.org/doc/stable/reference/generated/numpy.full.html): Return a new array of given shape and type, filled with fill_value.

[`np.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html): Return evenly spaced values within a given interval.

[`np.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html): Return evenly spaced numbers over a specified interval.


In [ ]:
# Method 2: Using NumPy functions
zeros_array = np.zeros(5)           # Array of zeros
ones_array = np.ones(5)             # Array of ones
full_array = np.full(5, 3.14)       # Array filled with specific value
range_array = np.arange(0, 10, 2)   # Array with range of values
linspace_array = np.linspace(0, 1, 5)  # Evenly spaced values

print("Zeros array:", zeros_array)
print("Ones array:", ones_array)
print("Full array (π):", full_array)
print("Range array (0-10, step 2):", range_array)
print("Linspace array (0-1, 5 points):", linspace_array)

Method 3: Random arrays

[`np.random.random()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html): Return random floats in the half-open interval [0.0, 1.0).

[`np.random.randint()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html): Return random integers from low (inclusive) to high (exclusive).

[`numpy.random.normal()`](https://numpy.org/doc/2.0/reference/random/generated/numpy.random.normal.html): Draw random samples from a normal (Gaussian) distribution.

In [ ]:
# Method 3: Random arrays
np.random.seed(42)  # For reproducible results
random_uniform = np.random.random(5)        # Uniform distribution [0,1)
random_normal = np.random.normal(0, 1, 5)   # Normal distribution (mean=0, std=1)
random_integers = np.random.randint(1, 11, 5)  # Random integers [1,10]

print("Random uniform [0,1):", random_uniform)
print("Random normal (μ=0, σ=1):", random_normal)
print("Random integers [1,10]:", random_integers)

### 💪 Practice: Array Creation
Create the following arrays:
1. An array of even numbers from 2 to 20
2. An array of 7 equally spaced values between -1 and 1
3. An array of 10 random integers between 50 and 100

In [7]:
# 1. Even numbers 2-20
## TODO

##approach 1
even_nums = np.arange(2,22,2)
print(even_nums)

##approach 2
even_nums2 = 2 * np.arange(1,11)
print(even_nums2)



[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [8]:
# 2. 7 values between -1 and 1
## TODO

even_spaced_array = np.linspace(-1,1,7)
print(even_spaced_array)


[-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.        ]


In [6]:
# 3. 10 random integers 50-100
## TODO

random_integers = np.random.randint(50, 101, 10)  # Random integers [1,10]
print(random_integers)


[78 56 86 80 79 99 80 81 72 75]


## 2: Initialize a Multi-dimensional NumPy Array

Create arrays with multiple dimensions:

[`np.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html): Create an array.

[`np.eye()`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html): Return a 2-D array with ones on the diagonal and zeros elsewhere.

[`np.diag()`](https://numpy.org/doc/stable/reference/generated/numpy.diag.html): Extract a diagonal or construct a diagonal array.

Shape properties:

[`.shape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html)

[`.ndim`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html)

[`.size`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html)

In [10]:
# Creating 2D arrays
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array from nested lists:")
print(array_2d)
print("Shape:", array_2d.shape) # (rows, columns)
print("Dimensions:", array_2d.ndim)
print("Size (total elements):", array_2d.size)

# Creating 3D arrays
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D array:")
print(array_3d)
print("Shape:", array_3d.shape)  # (depth, rows, columns)
print("Dimensions:", array_3d.ndim)
print("Size (total elements):", array_3d.size)

2D array from nested lists:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size (total elements): 6

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3
Size (total elements): 8


In [ ]:
# Initializing multi-dimensional arrays with specific values
zeros_2d = np.zeros((3, 4))          # 3 rows, 4 columns of zeros

print("3x4 zeros array:")
print(zeros_2d)

In [12]:
ones_3d = np.ones((2, 3, 4))         # 2x3x4 array of ones

print("\n2x3x4 ones array:")
print(ones_3d)
print("\n2x3x4 ones array shape:", ones_3d.shape)


2x3x4 ones array:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

2x3x4 ones array shape: (2, 3, 4)


In [11]:
full_2d = np.full((3, 3), 7)         # 3x3 array filled with 7

print("\n3x3 array filled with 7:")
print(full_2d)


3x3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [14]:
identity_matrix = np.eye(4)          # 4x4 identity matrix

print("\n4x4 identity matrix:")
print(identity_matrix)


4x4 identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
diagonal_matrix = np.diag([1, 2, 3, 4])  # Diagonal matrix

print("\nDiagonal matrix:")
print(diagonal_matrix)


Diagonal matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [16]:
# Random multi-dimensional arrays
np.random.seed(42)
random_2d = np.random.random((3, 4))      # Uniform [0,1)

print("Random 2D array (uniform):")
print(random_2d.round(2))

Random 2D array (uniform):
[[0.37 0.95 0.73 0.6 ]
 [0.16 0.16 0.06 0.87]
 [0.6  0.71 0.02 0.97]]


In [17]:
random_int_2d = np.random.randint(1, 10, (3, 4))  # Random integers between 1 and 9

print("\nRandom 2D integers [1,10):")
print(random_int_2d)


Random 2D integers [1,10):
[[6 2 5 1]
 [6 9 1 3]
 [7 4 9 3]]


In [18]:
normal_2d = np.random.normal(5, 2, (3, 4))  # Normal distribution (mean=5, std=2)
print("\nRandom 2D normal distribution:")
print(normal_2d.round(2))


Random 2D normal distribution:
[[5.83 6.66 4.41 4.94]
 [5.19 6.33 4.72 4.93]
 [3.5  3.44 6.9  8.16]]


### 💪 Practice: Multi-dimensional Array Creation
Create the following multi-dimensional arrays:
1. A 5x5 matrix where all elements equal 2.5
2. A 2x3x4 array of random numbers between 0 and 1
3. A 6x6 identity matrix
4. A 3x5 array of integers from 1 to 15

In [ ]:
## TODO
# 1. 5x5 matrix of 2.5





In [ ]:
## TODO
# 2. 2x3x4 random array





In [ ]:
## TODO
# 3. 6x6 identity matrix





In [ ]:
## TODO
# 4. 3x5 array of integers 1-15





## 3: Index and Slice into a NumPy Array

Access and modify specific elements or sections of arrays.

### 1D arrays

Indexing: `arr[index]`

Slicing: `arr[start:stop:step]`

In [19]:
# 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]) # What are alternative ways to create the array?
print("Original array:", arr)

# Single element access
print("First element (index 0):", arr[0])
print("Last element (index -1):", arr[-1])
print("Third element (index 2):", arr[2])


Original array: [10 20 30 40 50 60 70 80 90]
First element (index 0): 10
Last element (index -1): 90
Third element (index 2): 30


In [20]:
# Slicing syntax: start:stop:step
print("Elements 1-4 (arr[1:5]):", arr[1:5])
print("Every other element (arr[::2]):", arr[::2])
print("Last 3 elements (arr[-3:]):", arr[-3:])
print("Reverse array (arr[::-1]):", arr[::-1])

Elements 1-4 (arr[1:5]): [20 30 40 50]
Every other element (arr[::2]): [10 30 50 70 90]
Last 3 elements (arr[-3:]): [70 80 90]
Reverse array (arr[::-1]): [90 80 70 60 50 40 30 20 10]


### 2D Arrays

Indexing: `arr[row, col]`

Slicing: `arr[[start:stop], [start:stop]]`

In [ ]:
# Indexing and slicing 2D arrays
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("2D Matrix:")
print(matrix)

# Single element access: [row, column]
print("\nSingle element access:")
print("Element at [0,1]:", matrix[0, 1])
print("Element at [2,-1]:", matrix[2, -1])

In [ ]:
# Row and column access
print("\nRow and column access:")
print("First row:", matrix[0, :])      # or matrix[0]
print("Second column:", matrix[:, 1])
print("Last row:", matrix[-1, :])

In [ ]:
# Subarray slicing
print("\nSubarray slicing:")
print("Top-left 2x2:")
print(matrix[:2, :2])
print("Bottom-right 2x2:")
print(matrix[1:, 2:])

### Boolean indexing

Boolean indexing: `arr[arr > value]`

In [ ]:
# Boolean indexing
data = np.array([1, 5, 8, 3, 9, 2, 7, 4])
print("Original data:", data)

# Create boolean conditions
greater_than_5 = data > 5
print("Boolean mask (> 5):", greater_than_5)
print("Values > 5:", data[greater_than_5])


In [ ]:
# Multiple conditions
between_3_and_7 = (data >= 3) & (data <= 7)
print("Values between 3 and 7:", data[between_3_and_7])

# Modifying values with boolean indexing
data_copy = data.copy()
data_copy[data_copy > 6] = 999  # Replace values > 6 with 999
print("After replacing > 6 with 999:", data_copy)

### 💪 Practice: Indexing and Slicing
Given the array below, complete the following tasks:
1. Extract elements at indices 2, 4, and 6
2. Get every third element starting from index 1
3. Extract the middle 2x2 submatrix
4. Find all elements divisible by 3

In [ ]:
# Given arrays
arr_1d = np.array([12, 6, 18, 3, 9, 15, 21, 8, 24])
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print("1D array:", arr_1d)
print("2D array:")
print(arr_2d)

## TODO
# 1. Elements at indices 2, 4, 6




In [ ]:
## TODO
# 2. Every third element from index 1




In [ ]:
## TODO
# 3. Middle 2x2 submatrix




In [ ]:
## TODO
# 4. Elements divisible by 3




## 4: Reshape a Multi-dimensional NumPy Array

Change the shape of arrays while preserving the data.

Basic reshaping:

[`arr.reshape()`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html): Gives a new shape to an array without changing its data.

In [ ]:
# Basic reshaping
original = np.arange(1, 13)  # Numbers 1-12
print("Original 1D array:", original)
print("Shape:", original.shape)

In [ ]:
# Reshape to different 2D configurations
reshaped_3x4 = original.reshape(3, 4)
reshaped_4x3 = original.reshape(4, 3)
reshaped_2x6 = original.reshape(2, 6)

print(f"Reshaped to 3x4:\n {reshaped_3x4}")
print(f"Reshaped to 4X3:\n {reshaped_4x3}")
print(f"Reshaped to 2x6:\n {reshaped_2x6}")

In [ ]:
# Reshaping to 3D
array_24 = np.arange(1, 25)  # Numbers 1-24
print("Original array (24 elements):", array_24)

# Different 3D shapes
shape_2x3x4 = array_24.reshape(2, 3, 4)
print("\nReshaped to 2x3x4:")
print(shape_2x3x4)
print("Shape:", shape_2x3x4.shape)

shape_3x2x4 = array_24.reshape(3, 2, 4)
print("\nReshaped to 3x2x4:")
print(shape_3x2x4)
print("Shape:", shape_3x2x4.shape)

# how about an invalid/bad shape?

Automatic dimension:

[`arr.reshape()`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html): (-1, cols)


In [ ]:
# Using -1 for automatic dimension calculation
auto_reshape = np.arange(20)
print("Original array (20 elements):", auto_reshape)

# Let NumPy calculate one dimension automatically
auto_4x5 = auto_reshape.reshape(4, -1)  # 4 rows, auto-calculate columns
auto_5x4 = auto_reshape.reshape(-1, 4)  # Auto-calculate rows, 4 columns

print("\nReshape to 4x? (auto):")
print(auto_4x5)
print("Shape:", auto_4x5.shape)

print("\nReshape to ?x4 (auto):")
print(auto_5x4)
print("Shape:", auto_5x4.shape)



Flattening:

[`numpy.reshape()`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html): (-1)
[`numpy.ndarray.flatten()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html): Return a copy of the array collapsed into one dimension.


In [ ]:
# Flattening arrays (reshape to 1D)
matrix_to_flatten = np.array([[1, 2, 3], [4, 5, 6]])
flattened_reshape = matrix_to_flatten.reshape(-1)  # or .flatten() or .ravel()
print("\nOriginal matrix:")
print(matrix_to_flatten)
print("Flattened:", flattened_reshape)

### 💪 Practice: Reshaping Arrays
Given the array below:
1. Reshape it to a 6x5 matrix
2. Reshape it to a 3x2x5 3D array
3. Use automatic dimension calculation to create a matrix with 10 columns
4. Flatten the 6x5 matrix back to 1D

In [ ]:
# Given array with 30 elements
practice_array = np.arange(30)
print("Original array (30 elements):", practice_array)
print("Shape:", practice_array.shape)

## TODO
# 1. Reshape to 6x5



In [ ]:
## TODO
# 2. Reshape to 3x2x5



In [ ]:
## TODO
# 3. Auto-calculate rows with 10 columns



In [ ]:
## TODO
# 4. Flatten 6x5 matrix to 1D




## 5: Concatenate and Transpose a NumPy Array

Combine arrays and change their orientation.

### 5.1 Array Concatenation

[`np.concatenate()`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html): Join a sequence of arrays along an existing axis.

[`np.concat()`](https://numpy.org/doc/stable/reference/generated/numpy.concat.html): Join a sequence of arrays along an existing axis.

[`np.stack()`](https://numpy.org/doc/stable/reference/generated/numpy.stack.html): Join a sequence of arrays along a new axis.

[`np.hstack()`](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html): Stack arrays in sequence horizontally (column wise).

[`np.vstack()`](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html): Stack arrays in sequence vertically (row wise).

In [ ]:
# Concatenating 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)

# Concatenate along axis 0 (default for 1D)
concatenated = np.concatenate([arr1, arr2, arr3])
print("\nConcatenated w/ np.concatenate:", concatenated)
concatenated = np.concat([arr1, arr2, arr3])
print("\nConcatenated w/ np.concat:", concatenated)

In [ ]:
# Alternative methods for 1D arrays
using_hstack = np.hstack([arr1, arr2, arr3])
print("Using hstack:", using_hstack)

In [ ]:
# Concatenating 2D arrays
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_c = np.array([[9, 10]])

print("Matrix A:")
print(matrix_a)
print("Matrix B:")
print(matrix_b)
print("Matrix C:")
print(matrix_c)

In [ ]:
# Concatenate along different axes
concat_axis0 = np.concatenate([matrix_a, matrix_b], axis=0)  # Stack vertically
concat_axis1 = np.concatenate([matrix_a, matrix_b], axis=1)  # Stack horizontally

print("\nConcatenate along axis 0 (vertical):")
print(concat_axis0)
print("\nConcatenate along axis 1 (horizontal):")
print(concat_axis1)

In [ ]:
# Using vstack and hstack
v_stacked = np.vstack([matrix_a, matrix_b, matrix_c])
h_stacked = np.hstack([matrix_a, matrix_b])

print("\nVertical stack (vstack):")
print(v_stacked)
print("\nHorizontal stack (hstack):")
print(h_stacked)

### 5.2 Array Transposition

[`numpy.ndarray.T`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html): An attribute of an `numpy.ndarray` object.

[`numpy.transpose()`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html): Returns an array with axes transposed.


In [ ]:
# Basic transposition
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

print("Original matrix (2x4):")
print(matrix)
print("Shape:", matrix.shape)

# Transpose using .T attribute
transposed = matrix.T
print("\nTransposed matrix (4x2):")
print(transposed)
print("Shape:", transposed.shape)

In [ ]:
# Alternative transpose methods
transpose_method = matrix.transpose()
transpose_func = np.transpose(matrix)

print("\nAll transpose methods give same result:")
print("matrix.T equals matrix.transpose():", np.array_equal(transposed, transpose_method))
print("matrix.T equals np.transpose():", np.array_equal(transposed, transpose_func))

In [ ]:
# Transposing 3D arrays
array_3d = np.arange(24).reshape(2, 3, 4)
print("Original 3D array (2x3x4):")
print(array_3d)
print("Shape:", array_3d.shape)

# Default transpose reverses all axes
transposed_3d = array_3d.T
print("\nTransposed 3D array (4x3x2):")
print(transposed_3d)
print("Shape:", transposed_3d.shape)


In [ ]:
# Combining concatenation and transposition
data1 = np.array([[1, 2], [3, 4]])
data2 = np.array([[5, 6], [7, 8]])

print("Data 1:")
print(data1)
print("Data 2:")
print(data2)

# Concatenate then transpose
concat_then_transpose = np.vstack([data1, data2]).T
print("\nVertical concatenate then transpose:")
print(concat_then_transpose)


In [ ]:
# Transpose then concatenate
transpose_then_concat = np.hstack([data1.T, data2.T])
print("\nTranspose then horizontal concatenate:")
print(transpose_then_concat)

### 💪 Practice: Concatenation and Transposition
Work with the matrices below:
1. Concatenate A and B horizontally
2. Concatenate A and B vertically
3. Transpose matrix A
4. Transpose the result from step 1
5. Create a 4x6 matrix by concatenating A, B, and their transposes

In [ ]:
# Given matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix A (2x3):")
print(A)
print("Matrix B (2x3):")
print(B)

## TODO
# 1. Horizontal concatenation:




In [ ]:
## TODO
# 2. Vertical concatenation:




In [ ]:
## TODO
# 3. Transpose of A:




In [ ]:
## TODO
# 4. Transpose of horizontal concatenation:




In [ ]:
## TODO
# 5. 4x6 matrix using A, B, and their transposes:




## 🤗 Bonus: Math Functions in NumPy

[`numpy.sum()`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html): Sum of array elements over a given axis.

[`numpy.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html): Compute the arithmetic mean along the specified axis.

[`numpy.var()`](https://numpy.org/doc/stable/reference/generated/numpy.var.html): Compute the variance along the specified axis.

[`numpy.std()`](https://numpy.org/doc/stable/reference/generated/numpy.std.html): Compute the standard deviation along the specified axis.

In [ ]:
x = np.random.random((5, 4, 3))
y = np.sum(x) # By default, sums all axes
y

In [ ]:
y = np.sum(x, axis=0) # Sums 1st dimension
print(y.shape) # (4, 3)

y = np.sum(x, axis=2) # Sums 3rd dimension
print(y.shape) # (5, 4)

y = np.sum(x, axis=-1) # Also sums 3rd dimension
print(y.shape)

In [ ]:
y = np.sum(x, axis=(0, 1)) # Sums dimensions 1-2
print(y.shape) # What is the shape?
y

In [ ]:
y = np.mean(x) # By default, global mean
y = np.var(x)
y = np.std(x)

In [ ]:
y = np.mean(x, axis=0) # What is the shape of y ?
y = np.var(x, axis=0)
y = np.std(x, axis=0)

In [ ]:
y = np.mean(x, axis=(0, 2)) # What is the shape of y ?
y = np.var(x, axis=(0, 2))
y = np.std(x, axis=(0, 2))